"use client";

import { useState } from "react";

import { Button, Card, InferenceBadge, SectionHeading } from "@/components/ui";
import { relativeTime } from "@/lib/utils";
import type { AiInsights } from "@/types";

/**
 * AI insights, kept visibly separate from observed data.
 *
 * Everything in this panel is inference: it is labelled as such, it is
 * generated on request rather than up front, and nothing here feeds the score
 * (spec section 16).
 */
export function AiPanel({
  issueId,
  initial,
  enabled,
}: {
  issueId: string;
  initial: AiInsights | null;
  enabled: boolean;
}) {
  const [insights, setInsights] = useState<AiInsights | null>(initial);
  const [loading, setLoading] = useState(false);
  const [failed, setFailed] = useState(false);

  if (!enabled && !insights) return null;

  const generate = async () => {
    setLoading(true);
    setFailed(false);
    try {
      const response = await fetch(`/api/opportunities/${issueId}?ai=1`);
      const body = await response.json();
      const generated: AiInsights | null = body?.opportunity?.recommendation?.ai ?? null;
      if (generated) setInsights(generated);
      else setFailed(true);
    } catch {
      setFailed(true);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Card className="p-5">
      <SectionHeading hint={insights ? relativeTime(insights.generatedAt) : undefined}>
        <span className="flex items-center gap-2">
          Reading of the issue
          <InferenceBadge />
        </span>
      </SectionHeading>

      {!insights ? (
        <div className="space-y-3">
          <p className="text-sm text-ink-soft">
            An optional AI pass can summarise the issue, sketch an approach, and list what to verify
            before starting. It does not affect the score.
          </p>
          <Button onClick={generate} disabled={loading}>
            {loading ? "Reading…" : "Generate"}
          </Button>
          {failed ? (
            <p className="text-xs text-bad">
              The AI layer did not return anything usable. Everything above is unaffected.
            </p>
          ) : null}
        </div>
      ) : (
        <div className="space-y-4">
          {insights.summary ? (
            <p className="text-sm leading-relaxed text-ink-soft">{insights.summary}</p>
          ) : null}

          {insights.difficultyReasoning ? (
            <Block title="Why it looks this difficult">
              <p className="text-sm leading-relaxed text-ink-soft">
                {insights.difficultyReasoning}
              </p>
            </Block>
          ) : null}

          {insights.likelyFiles.length > 0 ? (
            <Block title="Files that may be involved">
              <ul className="space-y-1">
                {insights.likelyFiles.map((file) => (
                  <li key={file} className="font-mono text-xs text-ink-soft">
                    {file}
                  </li>
                ))}
              </ul>
            </Block>
          ) : null}

          {insights.contributionPlan.length > 0 ? (
            <Block title="Possible approach">
              <ol className="space-y-1.5">
                {insights.contributionPlan.map((step, index) => (
                  <li key={step} className="flex gap-2.5 text-sm text-ink-soft">
                    <span className="font-mono text-xs text-ink-faint tabular-nums">
                      {index + 1}.
                    </span>
                    <span>{step}</span>
                  </li>
                ))}
              </ol>
            </Block>
          ) : null}

          {insights.questionsToInvestigate.length > 0 ? (
            <Block title="Before starting, check">
              <ul className="space-y-1.5">
                {insights.questionsToInvestigate.map((question) => (
                  <li key={question} className="flex gap-2.5 text-sm text-ink-soft">
                    <span className="text-ink-faint">–</span>
                    <span>{question}</span>
                  </li>
                ))}
              </ul>
            </Block>
          ) : null}

          <p className="border-t border-line pt-3 text-xs text-ink-faint">
            Generated by {insights.provider}/{insights.model} from the issue text. Verify anything
            here against the repository before relying on it.
          </p>
        </div>
      )}
    </Card>
  );
}

function Block({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h3 className="mb-1.5 text-xs font-semibold tracking-[0.08em] text-ink-faint uppercase">
        {title}
      </h3>
      {children}
    </div>
  );
}
